on:
  pull_request:
    branches:
    - dev

jobs:
  build_camunda:
    name: build camunda
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v3.10.0
      with:
        java-version: 19
        distribution: oracle
        java-package: jdk
    - name: Build camunda
      run: |
        cd ./engine/camunda
        mvn -B package --file pom.xml
